# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from darknet_ros_msgs/BoundingBox.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BoundingBox(genpy.Message):
  _md5sum = "b7c471f7e43701288329c5fdd129b1f2"
  _type = "darknet_ros_msgs/BoundingBox"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string Class
float64 probability
int64 xmin
int64 ymin
int64 xmax
int64 ymax
float32 X
float32 Y
float32 Z
bool Invalid
"""
  __slots__ = ['Class','probability','xmin','ymin','xmax','ymax','X','Y','Z','Invalid']
  _slot_types = ['string','float64','int64','int64','int64','int64','float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Class,probability,xmin,ymin,xmax,ymax,X,Y,Z,Invalid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BoundingBox, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Class is None:
        self.Class = ''
      if self.probability is None:
        self.probability = 0.
      if self.xmin is None:
        self.xmin = 0
      if self.ymin is None:
        self.ymin = 0
      if self.xmax is None:
        self.xmax = 0
      if self.ymax is None:
        self.ymax = 0
      if self.X is None:
        self.X = 0.
      if self.Y is None:
        self.Y = 0.
      if self.Z is None:
        self.Z = 0.
      if self.Invalid is None:
        self.Invalid = False
    else:
      self.Class = ''
      self.probability = 0.
      self.xmin = 0
      self.ymin = 0
      self.xmax = 0
      self.ymax = 0
      self.X = 0.
      self.Y = 0.
      self.Z = 0.
      self.Invalid = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.Class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d4q3fB().pack(_x.probability, _x.xmin, _x.ymin, _x.xmax, _x.ymax, _x.X, _x.Y, _x.Z, _x.Invalid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Class = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Class = str[start:end]
      _x = self
      start = end
      end += 53
      (_x.probability, _x.xmin, _x.ymin, _x.xmax, _x.ymax, _x.X, _x.Y, _x.Z, _x.Invalid,) = _get_struct_d4q3fB().unpack(str[start:end])
      self.Invalid = bool(self.Invalid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.Class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d4q3fB().pack(_x.probability, _x.xmin, _x.ymin, _x.xmax, _x.ymax, _x.X, _x.Y, _x.Z, _x.Invalid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Class = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Class = str[start:end]
      _x = self
      start = end
      end += 53
      (_x.probability, _x.xmin, _x.ymin, _x.xmax, _x.ymax, _x.X, _x.Y, _x.Z, _x.Invalid,) = _get_struct_d4q3fB().unpack(str[start:end])
      self.Invalid = bool(self.Invalid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d4q3fB = None
def _get_struct_d4q3fB():
    global _struct_d4q3fB
    if _struct_d4q3fB is None:
        _struct_d4q3fB = struct.Struct("<d4q3fB")
    return _struct_d4q3fB
